# Generated by Django 4.0.4 on 2022-06-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstaApp', '0002_comment_user_image_user_likes_user_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date_posted']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
