# Generated by Django 4.0.4 on 2022-06-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstaApp', '0004_alter_comment_user_alter_image_user_alter_likes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='InstaApp.profile'),
        ),
    ]
