# Generated by Django 4.0.4 on 2022-06-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaApp', '0005_alter_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
